apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: ${SECRET_KEY_ENV} # Reference to environment variable
  DB_PASSWORD: ${DB_PASSWORD_ENV} # Reference to environment variable